[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "default"
explorer_url = "https://eth-sepolia.blockcscout.com/"
explorer_type = "blockscout"
chain_id = 11155111


[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
deployer_script = "script/deploy_mocks.py"


[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337



[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
